import {Citation} from './citation';
export const exemplo:Citation[]=[
    {id:1, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 1",content:"etc..." },
    {id:2, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:3, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 3",content:"etc..."},
    {id:4, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 4",content:"etc..." },
    {id:5, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:6, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 2",content:"etc..."},
    {id:7, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 3",content:"etc..." },
    {id:8, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 1",content:"etc..."},
    {id:9, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 1",content:"etc..."},
    {id:10, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada...",assunto:"Assunto 3",content:"etc..." },
    {id:11, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...", assunto:"Assunto 4",content:"etc..."},
    {id:12, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 4",content:"etc..."},
    {id:13, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 1",content:"etc..." },
    {id:14, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:15, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 3",content:"etc..."},
    {id:16, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 4" ,content:"etc..."},
    {id:17, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:18, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 2",content:"etc..."},
    {id:19, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 3",content:"etc..." },
    {id:20, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 1",content:"etc..." },
    {id:21, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:22, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 3",content:"etc..."},
    {id:23, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 4",content:"etc..." },
    {id:24, titulo:"O Senhor salva a todos", ref:"Zacarias 8.6-8", comment:"Há Salvação para todos...",assunto:"Assunto 2",content:"etc..."},
    {id:25, titulo:"Siga e espere por Jesus", ref:"Mateus 14.14", comment:"Devemos seguir a Jesus...",assunto:"Assunto 2",content:"etc..."},
    {id:26, titulo:"Não tenha medo", ref:"Isaías 41.12,13", comment:"Não precisamos ter medo de nada..." ,assunto:"Assunto 3",content:"etc..." },
  ];